export const CHECK_CONVERSION = 'App/CHECK_CONVERSION';
export const CHECK_CONVERSION_SUCCESS = 'App/CHECK_CONVERSION_SUCCESS';
export const CHECK_CONVERSION_ERROR = 'App/CHECK_CONVERSION_ERROR';

export const CALCULATION = 'App/CALCULATION';
export const CALCULATION_SUCCESS = 'App/CALCULATION_SUCCESS';
export const CALCULATION_ERROR = 'App/CALCULATION_ERROR';
